### ISSUE TITLE
More structure necessary

### ISSUE THREAD

**Issue by SignisAura** [PythonDataScience24/Harmony-Hootenanny#2]
In my opinion, the project structure is not optimal.

I'm not able to easily find any implementation of data science related code:
I cannot find any way to analyse data with a GUI or file.
Additionally, I assume the relevant code is distributed in the front-end and back-end directory.

I would recommend creating a directory where all code concerning data science is stored. It would be much easier to inspect it .

**Comment by M4anuel** [comment]
Hey there, thank you for your comment!

You couldn't find code closely related data science because it hadn't been implemented by then (`matplotlib` usage and such). You can find it in [this file](https://github.com/PythonDataScience24/Harmony-Hootenanny/blob/main/backend/generatePlots.py). Yes, there is a lot you can still criticize there...

However the code for gathering data is not distributed between the frontend and the backend. All requests that are made by users are tracked in the backend and filled into the database trough [database.py](https://github.com/PythonDataScience24/Harmony-Hootenanny/blob/main/backend/database.py).

I disagree that we should put all our code concerning data science in one directory, since this would include the `database` file, the `websocket` file and the `api` /`routes` file, which would disorganize the structure of a good backend where responsibilities are well distributed and clear to backend devs what they do.
